[control_plane]
ghaith-vmware-virtual-platform ansible_host=192.168.211.140 ansible_user=ghaith

[workers]
worker-vmware-virtual-platform ansible_host=192.168.211.142 ansible_user=worker

[k8s_nodes:children]
control_plane
workers
